package com.bank.bian.capitalmanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Capital Management
 *
 * Business Area:      Business Support
 * Business Domain:    Finance
 * Functional Pattern: Manage
 * Asset Type:         Capital Plan
 * Control Record:     Capital Plan Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Capital Management — BIAN Semantic API")
                .description("Service Domain 'Capital Management' (Manage pattern) "
                        + "operating on the 'Capital Plan Management Plan' control record.")
                .version("0.1.0"));
    }
}
